#cloud-config
package_update: true
packages:
  - aws-cfn-bootstrap
write_files:
  - path: "/etc/ecs/ecs.config"
    permissions: "0744"
    owner: "root"
    content: |
      ECS_CLUSTER=${ecs_cluster_name}
      ECS_LOG_LEVEL=${ecs_log_level}
      ECS_ENABLE_CONTAINER_METADATA=true
      ECS_ENABLE_TASK_IAM_ROLE=true
      ECS_ENABLE_TASK_IAM_ROLE_NETWORK_HOST=true
      ECS_AVAILABLE_LOGGING_DRIVERS='["awslogs"]'

  - path: "/usr/local/scripts/cloudformation-signal.sh"
    permissions: "0744"
    owner: "root"
    content: |
      #! /bin/bash

      set -euo pipefail

      function await_process() {
        echo -n "Waiting for $1..."
        while ! pgrep -f "$1" > /dev/null; do
          sleep 1
        done
        echo "Done!"
      }
      await_process "/usr/libexec/amazon-ecs-init start"

runcmd:
  - |
    start ecs
  - |
    /usr/local/scripts/cloudformation-signal.sh
    /opt/aws/bin/cfn-signal -e $? --stack ${stack_name} --resource AutoScalingGroup --region ${region}
