#cloud-config
package_update: true
packages:
  - awslogs
write_files:
  - path: "/concourse/keys/web/tsa_host_key"
    permissions: "0644"
    owner: "root"
    encoding: base64
    content: ${base64encode(tsa_host_key)}
  - path: "/concourse/keys/web/session_signing_key"
    permissions: "0644"
    owner: "root"
    encoding: base64
    content: ${base64encode(session_signing_key)}
  - path: "/concourse/keys/web/authorized_worker_keys"
    permissions: "0644"
    owner: "root"
    encoding: base64
    content: ${base64encode(authorized_worker_keys)}
  - path: "/etc/awslogs/awscli.template"
    permissions: "0644"
    owner: "root"
    content: |
      [plugins]
      cwlogs = cwlogs
      [default]
      region = ${log_group_region}
  - path: "/etc/awslogs/awslogs.template"
    permissions: "0644"
    owner: "root"
    content: |
      [general]
      state_file = /var/lib/awslogs/agent-state

      [/var/log/concourse.log]
      file = /var/log/concourse.log
      log_group_name = ${log_group_name}
      log_stream_name = {instance_id}
  - path: "/etc/systemd/system/concourse.service"
    permissions: "0644"
    owner: "root"
    content: |
      [Unit]
      Description=Service for Concourse ATC/TSA
      Requires=network-online.target
      After=network-online.target

      [Service]
      Restart=always
      RestartSec=30s
      TimeoutStartSec=5m
      StandardOutput=syslog
      StandardError=syslog
      SyslogIdentifier=concourse

      Environment="CONCOURSE_GITHUB_AUTH_CLIENT_ID=${github_client_id}"
      Environment="CONCOURSE_GITHUB_AUTH_CLIENT_SECRET=${github_client_secret}"
      Environment="CONCOURSE_GITHUB_AUTH_USER=${github_users}"
      Environment="CONCOURSE_GITHUB_AUTH_TEAM=${github_teams}"
      Environment="CONCOURSE_POSTGRES_DATA_SOURCE=${concourse_postgres_source}"
      Environment="CONCOURSE_EXTERNAL_URL=${concourse_web_host}"
      Environment="CONCOURSE_LOG_LEVEL=${log_level}"
      Environment="CONCOURSE_TSA_LOG_LEVEL=${log_level}"
      Environment="CONCOURSE_VAULT_URL=${vault_url}"
      Environment="CONCOURSE_VAULT_CLIENT_TOKEN=${vault_client_token}"
      Environment="CONCOURSE_TSA_HOST_KEY=/concourse/keys/web/tsa_host_key"
      Environment="CONCOURSE_TSA_AUTHORIZED_KEYS=/concourse/keys/web/authorized_worker_keys"
      Environment="CONCOURSE_SESSION_SIGNING_KEY=/concourse/keys/web/session_signing_key"
      Environment="CONCOURSE_ENCRYPTION_KEY=${encryption_key}"
      Environment="CONCOURSE_OLD_ENCRYPTION_KEY=${old_encryption_key}"

      ExecStartPre=/bin/bash -c "/bin/systemctl set-environment CONCOURSE_PEER_URL=http://$(curl -L http://169.254.169.254/latest/meta-data/local-ipv4):8080"
      ExecStart=/usr/local/bin/concourse web

      [Install]
      WantedBy=multi-user.target
  - path: "/etc/systemd/system/concourse-logging.service"
    permissions: "0644"
    owner: "root"
    content: |
      [Unit]
      Description=Service for Concourse logging
      After=rc-local.service

      [Service]
      Type=simple
      Restart=always
      TimeoutSec=infinity
      SyslogIdentifier=concourse

      ExecStart=/bin/bash -c '/usr/bin/journalctl -u concourse --no-tail -f -o cat > /var/log/concourse.log'

      [Install]
      WantedBy=multi-user.target
runcmd:
  - |
    systemctl disable amazon-ssm-agent.service
  - |
    curl -L "${concourse_download_url}" > /usr/local/bin/concourse
    chmod 0755 /usr/local/bin/concourse
    chown root:root /usr/local/bin/concourse
  - |
    cp /etc/awslogs/awscli.template /etc/awslogs/awscli.conf
    cp /etc/awslogs/awslogs.template /etc/awslogs/awslogs.conf
  - |
    systemctl enable concourse-logging.service --now
    systemctl enable awslogsd.service --now
    systemctl enable concourse.service --now
