#cloud-config
write_files:
  - path: "/concourse/keys/worker/tsa_host_key.pub"
    permissions: "0644"
    owner: "root"
    encoding: base64
    content: ${base64encode(pub_tsa_host_key)}
  - path: "/concourse/keys/worker/worker_key"
    permissions: "0644"
    owner: "root"
    encoding: base64
    content: ${base64encode(worker_key)}
  - path: "/concourse/keys/worker/worker_key.pub"
    permissions: "0644"
    owner: "root"
    encoding: base64
    content: ${base64encode(pub_worker_key)}
coreos:
  update:
    reboot-strategy: "reboot"
  locksmith:
    window-start: 02:00
    window-length: 6h
  units:
   - name: cloudwatch-monitor.service
     command: start
     runtime: true
     content: |
       [Unit]
       Description=Cloudwatch monitoring.
       Documentation=https://github.com/a3linux/go-aws-mon/
       Requires=docker.socket
       After=docker.socket
       [Service]
       Type=oneshot
       SyslogIdentifier=cloudwatch-monitor
       ExecStartPre=-/usr/bin/docker kill cloudwatch-monitor
       ExecStartPre=-/usr/bin/docker rm cloudwatch-monitor
       ExecStartPre=/usr/bin/docker pull a3linux/go-aws-mon:latest
       ExecStart=/usr/bin/docker run --name cloudwatch-monitor \
                                     --volume=/etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/certificates.crt \
                                     --volume=/var/log:/var/log \
                                     a3linux/go-aws-mon /usr/bin/go-aws-mon \
                                     --mem-used \
                                     --mem-avail \
                                     --disk-space-used \
                                     --disk-space-avail \
                                     --disk-inode-util \
                                     --disk-path=/,/var/lib
   - name: cloudwatch-monitor.timer
     enable: true
     command: start
     content: |
      [Unit]
      Description=Cloudwatch logging every minute.
      [Timer]
      OnBootSec=0m
      OnCalendar=minutely
   - name: concourse-worker.service
     command: start
     runtime: true
     content: |
       [Unit]
       Description=Concourse
       Documentation=https://hub.docker.com/r/concourse/concourse/
       Requires=docker.socket
       After=docker.socket
       [Service]
       EnvironmentFile=/etc/environment
       Restart=always
       RestartSec=30s
       TimeoutStartSec=5m
       SyslogIdentifier=concourse-worker
       ExecStartPre=-/usr/bin/docker kill concourse-worker
       ExecStartPre=-/usr/bin/docker rm concourse-worker
       ExecStartPre=/usr/bin/docker pull ${image_repository}:${image_version}
       ExecStart=/usr/bin/docker run --name concourse-worker \
                                     --volume=/var/run/docker.sock:/var/run/docker.sock \
                                     --volume=/concourse/keys/worker:/concourse-keys \
                                     --volume=/concourse:/concourse \
                                     --privileged \
                                     --publish=7777:7777 \
                                     --publish=7788:7788 \
                                     --env=CONCOURSE_WORK_DIR=/concourse \
                                     --env=CONCOURSE_TSA_HOST=${concourse_tsa_host} \
                                     --env=CONCOURSE_PEER_IP=$${COREOS_PRIVATE_IPV4} \
                                     --env=CONCOURSE_BIND_IP=0.0.0.0 \
                                     --env=CONCOURSE_BAGGAGECLAIM_BIND_IP=0.0.0.0 \
                                     --env=CONCOURSE_BAGGAGECLAIM_LOG_LEVEL=${log_level} \
                                     --log-driver=awslogs \
                                     --log-opt awslogs-region=${log_group_region} \
                                     --log-opt awslogs-group=${log_group_name} \
                                     ${image_repository}:${image_version} \
                                     worker
