#cloud-config
package_update: true
packages:
  - awslogs
  - aws-cfn-bootstrap
write_files:
  - path: "/concourse/keys/worker/tsa_host_key.pub"
    permissions: "0644"
    owner: "root"
    encoding: base64
    content: ${base64encode(pub_tsa_host_key)}
  - path: "/concourse/keys/worker/worker_key"
    permissions: "0644"
    owner: "root"
    encoding: base64
    content: ${base64encode(worker_key)}
  - path: "/concourse/keys/worker/worker_key.pub"
    permissions: "0644"
    owner: "root"
    encoding: base64
    content: ${base64encode(pub_worker_key)}
  - path: "/etc/awslogs/awscli.template"
    permissions: "0644"
    owner: "root"
    content: |
      [plugins]
      cwlogs = cwlogs
      [default]
      region = ${region}
  - path: "/etc/awslogs/awslogs.template"
    permissions: "0644"
    owner: "root"
    content: |
      [general]
      state_file = /var/lib/awslogs/agent-state

      [/var/log/concourse.log]
      file = /var/log/concourse.log
      log_group_name = ${log_group_name}
      log_stream_name = {instance_id}
  - path: "/etc/systemd/system/concourse.service"
    permissions: "0644"
    owner: "root"
    content: |
      [Unit]
      Description=Service for Concourse Worker
      Requires=network-online.target
      After=network-online.target

      [Service]
      Restart=always
      RestartSec=30s
      TimeoutStartSec=5m
      TimeoutStopSec=1h
      StandardOutput=syslog
      StandardError=syslog
      SyslogIdentifier=concourse

      Environment="CONCOURSE_BIND_IP=0.0.0.0"
      Environment="CONCOURSE_WORK_DIR=/concourse"
      Environment="CONCOURSE_TSA_HOST=${concourse_tsa_host}"
      Environment="CONCOURSE_BAGGAGECLAIM_BIND_IP=0.0.0.0"
      Environment="CONCOURSE_BAGGAGECLAIM_LOG_LEVEL=${log_level}"
      Environment="CONCOURSE_TSA_PUBLIC_KEY=/concourse/keys/worker/tsa_host_key.pub"
      Environment="CONCOURSE_TSA_WORKER_PRIVATE_KEY=/concourse/keys/worker/worker_key"

      ExecStartPre=/bin/bash -c "/bin/systemctl set-environment CONCOURSE_NAME=$(curl -L http://169.254.169.254/latest/meta-data/instance-id)"
      ExecStartPre=/bin/bash -c "/bin/systemctl set-environment CONCOURSE_PEER_IP=$(curl -L http://169.254.169.254/latest/meta-data/local-ipv4)"
      ExecStart=/usr/local/bin/concourse worker

      ExecStop=/usr/local/bin/concourse retire-worker
      ExecStop=/bin/bash -c "while pgrep -u root -f '^/concourse/.*/assets/bin/runc' > /dev/null; do sleep 1; done"
      ExecStop=/bin/kill -15 $MAINPID

      [Install]
      WantedBy=multi-user.target
  - path: "/etc/systemd/system/concourse-logging.service"
    permissions: "0644"
    owner: "root"
    content: |
      [Unit]
      Description=Service for Concourse logging
      After=rc-local.service

      [Service]
      Type=simple
      Restart=always
      TimeoutSec=infinity
      SyslogIdentifier=concourse

      ExecStart=/bin/bash -c '/usr/bin/journalctl -u concourse --no-tail -f -o cat > /var/log/concourse.log'

      [Install]
      WantedBy=multi-user.target
  - path: "/var/tmp/concourse-signal.sh"
    permissions: "0744"
    owner: "root"
    content: |
      #! /usr/bin/bash

      set -euo pipefail

      while ! systemctl is-active concourse.service > /dev/null; do
          sleep 1
      done
runcmd:
  - |
    systemctl disable amazon-ssm-agent.service
  - |
    curl -L "${concourse_download_url}" > /usr/local/bin/concourse
    chmod 0755 /usr/local/bin/concourse
    chown root:root /usr/local/bin/concourse
  - |
    cp /etc/awslogs/awscli.template /etc/awslogs/awscli.conf
    cp /etc/awslogs/awslogs.template /etc/awslogs/awslogs.conf
  - |
    systemctl enable concourse-logging.service --now
    systemctl enable awslogsd.service --now
    systemctl enable concourse.service --now
  - |
    /var/tmp/concourse-signal.sh
    /opt/aws/bin/cfn-signal -e $? --stack ${stack_name} --resource AutoScalingGroup --region ${region}
